# Generated by Django 4.0 on 2022-03-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('technology', '0002_buildingprofile_tos_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingprofile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
