# Generated by Django 3.2.7 on 2022-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0008_auto_20220322_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='economic',
            name='battery_costs_for_maintenance_and_operations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='battery_costs_perkW_inverter_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='battery_costs_perkWh_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='battery_lifetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='hydrogen_costs_for_maintenance_and_operations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='hydrogen_costs_perkw_electrolyseur_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='hydrogen_costs_perkw_fuel_cellpower',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='hydrogen_costsperkWh_hydrogencapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='hydrogen_interest_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='hydrogen_lifetime',
            field=models.IntegerField(null=True),
        ),
    ]
