# Generated by Django 4.0.3 on 2022-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0010_economic_tos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic',
            name='battery_costs_for_maintenance_and_operations',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='battery_costs_perkW_inverter_power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='battery_costs_perkWh_capacity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='battery_lifetime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='electricity_costs_per_kWh',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='electricity_feed_in_tariff_chp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='electricity_feed_in_tariff_for_photovoltaic',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='electricity_fixed_costs_per_year',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='hydrogen_costs_for_maintenance_and_operations',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='hydrogen_costs_perkw_electrolyseur_power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='hydrogen_costs_perkw_fuel_cellpower',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='hydrogen_costsperkWh_hydrogencapacity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='hydrogen_interest_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='hydrogen_lifetime',
            field=models.FloatField(null=True),
        ),
    ]
