# Generated by Django 4.0.3 on 2022-03-23 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_search_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technology', '0012_delete_economic'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingprofile',
            name='address_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.address'),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='address_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.address'),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='building_type_de',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='building_type_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='buildingsizei_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='buildingsizei_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='dhwenergyconsumptioni_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='dhwenergyconsumptioni_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='electricalenergyconsumptioni_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='electricalenergyconsumptioni_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='numofusers_de',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='numofusers_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='user_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
