# Generated by Django 3.2.7 on 2022-03-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0013_buildingprofile_address_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingprofile',
            name='address_de',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='building_type_de',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='building_type_en',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='buildingsizei_de',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='buildingsizei_en',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='dhwenergyconsumptioni_de',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='dhwenergyconsumptioni_en',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='electricalenergyconsumptioni_de',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='electricalenergyconsumptioni_en',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='numofusers_de',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='numofusers_en',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='user_de',
        ),
        migrations.RemoveField(
            model_name='buildingprofile',
            name='user_en',
        ),
    ]
