# Generated by Django 4.0.3 on 2022-03-15 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_rename_user_id_search_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Address',
        ),
    ]
