# Generated by Django 4.0 on 2022-03-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=20)),
                ('numofusers', models.IntegerField(null=True)),
                ('electricalenergyconsumptioni', models.IntegerField(null=True)),
                ('dhwenergyconsumptioni', models.IntegerField(null=True)),
                ('buildingsizei', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tos',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technology.buildingprofile'),
        ),
    ]
