# Generated by Django 3.2.7 on 2022-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0006_economic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic',
            name='electricity_costs_per_kWh',
            field=models.IntegerField(null=True),
        ),
    ]
