# Generated by Django 3.2.7 on 2022-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0007_alter_economic_electricity_costs_per_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='economic',
            name='gas_costs_per_kwh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='economic',
            name='gas_fixed_costs_per_year',
            field=models.IntegerField(null=True),
        ),
    ]
