# Generated by Django 4.0.3 on 2022-03-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0011_alter_economic_battery_costs_for_maintenance_and_operations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Economic',
        ),
    ]
