# Generated by Django 3.2.9 on 2022-02-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesis', '0002_auto_20220224_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numofpersons', models.PositiveIntegerField(null=True)),
                ('electricalenergyconsumption', models.FloatField(null=True)),
                ('thermalbuildingstandard', models.CharField(max_length=20, null=True)),
                ('buildingsize', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
