# Generated by Django 3.2.9 on 2022-02-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_sfh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfh',
            old_name='thermalbuildingstandard',
            new_name='dhwenergyconsumption',
        ),
    ]
