# Generated by Django 3.2.9 on 2022-03-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_alter_sfh_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sfh',
            options={},
        ),
        migrations.AlterField(
            model_name='sfh',
            name='buildingsize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sfh',
            name='dhwenergyconsumption',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sfh',
            name='electricalenergyconsumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sfh',
            name='numofpersons',
            field=models.IntegerField(null=True),
        ),
    ]
