# Generated by Django 3.2.9 on 2022-03-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_auto_20220302_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chpcombinedheatpower', models.CharField(max_length=20, null=True)),
                ('chpoperationstrategy', models.CharField(max_length=20, null=True)),
                ('heatpumptechnology', models.CharField(max_length=20, null=True)),
                ('heatpumpmodel', models.CharField(max_length=20, null=True)),
                ('bsfeedinlimitation', models.FloatField(null=True)),
                ('bsusablecapacity', models.FloatField(null=True)),
                ('bsratedpower', models.FloatField(null=True)),
                ('hsusablecapacity', models.IntegerField(null=True)),
                ('hsratedpower', models.IntegerField(null=True)),
                ('elvehiclesdistance', models.IntegerField(null=True)),
            ],
        ),
    ]
