# Generated by Django 3.2.9 on 2022-03-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0009_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tos',
            name='azimut',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tos',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tos',
            name='installedgenpower',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tos',
            name='ratedinverterpower',
            field=models.IntegerField(null=True),
        ),
    ]
