# Generated by Django 3.2.9 on 2022-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0012_tos_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingprofile',
            name='technology',
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='technology',
            field=models.ManyToManyField(related_name='Technology', to='thesis.Tos'),
        ),
    ]
