# Generated by Django 3.2.9 on 2022-02-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batterystorage',
        ),
        migrations.DeleteModel(
            name='Chp',
        ),
        migrations.DeleteModel(
            name='Electricvehicles',
        ),
        migrations.DeleteModel(
            name='Gasheater',
        ),
        migrations.DeleteModel(
            name='Heatpump',
        ),
        migrations.DeleteModel(
            name='Hydrogenstorage',
        ),
        migrations.DeleteModel(
            name='Mfh',
        ),
        migrations.DeleteModel(
            name='Photovoltaic',
        ),
        migrations.DeleteModel(
            name='Sfh',
        ),
    ]
