# Generated by Django 3.2.9 on 2022-03-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_rename_thermalbuildingstandard_sfh_dhwenergyconsumption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sfh',
            options={'ordering': ['numofpersons']},
        ),
    ]
