# Generated by Django 3.2.9 on 2022-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_auto_20220302_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mfh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numofdwellings', models.IntegerField(null=True)),
                ('thermalbuildingstandard', models.IntegerField(null=True)),
                ('electricalenergyconsumption', models.IntegerField(null=True)),
                ('dhwenergyconsumption', models.IntegerField(max_length=20, null=True)),
                ('buildingsize', models.IntegerField(null=True)),
            ],
        ),
    ]
