# Generated by Django 3.2.9 on 2022-03-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_mfh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricalenergyconsumption', models.IntegerField(null=True)),
                ('electricalenergyprofiletype', models.CharField(max_length=20, null=True)),
                ('thermalbuildingtype', models.IntegerField(null=True)),
                ('buildingsize', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mfh',
            name='dhwenergyconsumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sfh',
            name='dhwenergyconsumption',
            field=models.IntegerField(null=True),
        ),
    ]
