# Generated by Django 3.2.9 on 2022-03-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_auto_20220303_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=20)),
                ('numofusers', models.IntegerField(null=True)),
                ('electricalenergyconsumption', models.IntegerField(null=True)),
                ('energyconsumption', models.IntegerField(null=True)),
                ('buildingsize', models.IntegerField(null=True)),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.tos')),
            ],
        ),
    ]
