# Generated by Django 3.2.9 on 2022-03-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0013_auto_20220308_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingprofile',
            old_name='electricalenergyconsumption',
            new_name='electricalenergyconsumptioni',
        ),
    ]
