# Generated by Django 3.2.9 on 2022-03-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0014_rename_electricalenergyconsumption_buildingprofile_electricalenergyconsumptioni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingprofile',
            old_name='buildingsize',
            new_name='buildingsizei',
        ),
        migrations.RenameField(
            model_name='buildingprofile',
            old_name='energyconsumption',
            new_name='dhwenergyconsumptioni',
        ),
    ]
