# Generated by Django 3.2.9 on 2022-03-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0015_auto_20220308_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingprofile',
            name='technology',
            field=models.ManyToManyField(related_name='technology', to='thesis.Tos'),
        ),
    ]
