# Generated by Django 4.0 on 2022-03-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0016_alter_buildingprofile_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingprofile',
            name='technology',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.DeleteModel(
            name='Mfh',
        ),
        migrations.DeleteModel(
            name='Sfh',
        ),
        migrations.DeleteModel(
            name='BuildingProfile',
        ),
        migrations.DeleteModel(
            name='Tos',
        ),
    ]
